services:
  mongodb:
    image: mongo:5.0.10
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017

  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - mongodb
    command: mongodb:27017
    environment:
      - TIMEOUT_LENGTH=10
